# Generated by Django 2.1.5 on 2019-02-07 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('Médecine nucléaire', 'MN'), ('Radiologie diagnostique', 'RD'), ('Chirurgie générale', 'CG'), ('Médecine interne générale', 'MIG')], max_length=25)),
                ('establishment', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mammography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection_donnees.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='mammography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection_donnees.Mammography'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection_donnees.Doctor'),
        ),
    ]
