# Generated by Django 2.1.5 on 2019-03-30 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection_donnees', '0002_auto_20190207_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mammography',
            name='titre',
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_establishment',
            field=models.CharField(default=datetime.datetime(2019, 3, 30, 10, 58, 25, 858351, tzinfo=utc), max_length=15),
            preserve_default=False,
        ),
    ]
