# Generated by Django 2.1.5 on 2019-03-30 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection_donnees', '0003_auto_20190330_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 30, 11, 10, 36, 487083, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
