# Generated by Django 2.1.5 on 2019-03-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_donnees', '0004_diagnostic_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mammography',
            name='momography',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
