# Generated by Django 2.1.5 on 2019-03-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_donnees', '0005_mammography_momography'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name=''),
        ),
    ]
