# Generated by Django 2.1.5 on 2019-03-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_donnees', '0006_doctor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(max_length=250),
        ),
    ]
